platform: template
switches:

  kitchen_tv_power:
    value_template: >
      {% if is_state('media_player.kitchen_tv', 'on') %}
        true
      {% else %}
        false
      {% endif %}
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.power
    turn_off:
      service: switch.turn_on
      data:
        entity_id: switch.power

  kitchen_automations:
    friendly_name: 'Автоматизации на кухне'
    value_template: >
      {% if is_state('group.kitchen_automations', 'off') and is_state('switch.flux', 'off') %}
        false
      {% else %}
        true
      {% endif %}
    turn_on:
      - service: switch.turn_on
        data:
          entity_id: switch.flux
      - service: automation.turn_on
        data:
          entity_id: group.kitchen_automations
    turn_off:
      - service: switch.turn_off
        data:
          entity_id: switch.flux
      - service: automation.turn_off
        data:
          entity_id: group.kitchen_automations

  server_automation:
    friendly_name: 'Автоматическое включение/выключение'
    value_template: >
      {% if is_state('group.server', 'off') %}
        false
      {% else %}
        true
      {% endif %}
    turn_on:
      service: automation.turn_on
      data:
        entity_id: group.server
    turn_off:
      service: automation.turn_off
      data:
        entity_id: group.server