platform: template
switches:
  kitchen_tv_power:
    value_template: >
      {% if is_state('media_player.kitchen_tv', 'on') %}
        true
      {% else %}
        false
      {% endif %}
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.power
    turn_off:
      service: switch.turn_on
      data:
        entity_id: switch.power
  kitchen_automations_light:
    value_template: >
      {% if is_state('automation.kitchen_light_on', 'off') or is_state('automation.kitchen_light_off', 'off') %}
        false
      {% else %}
        true
      {% endif %}
    turn_on:
      service: automation.turn_on
      data:
        entity_id: automation.kitchen_light_on, automation.kitchen_light_off
    turn_off:
      service: automation.turn_off
      data:
        entity_id: automation.kitchen_light_on, automation.kitchen_light_off
  kitchen_automations_nightlight:
    value_template: >
      {% if is_state('automation.kitchen_nightlight_on', 'off') or is_state('automation.kitchen_nightlight_off', 'off') %}
        false
      {% else %}
        true
      {% endif %}
    turn_on:
      service: automation.turn_on
      data:
        entity_id: automation.kitchen_nightlight_on, automation.kitchen_nightlight_off
    turn_off:
      service: automation.turn_off
      data:
        entity_id: automation.kitchen_nightlight_on, automation.kitchen_nightlight_off
  server_automation:
    friendly_name: 'Автоматическое включение/выключение'
    value_template: >
      {% if is_state('group.server', 'off') %}
        false
      {% else %}
        true
      {% endif %}
    turn_on:
      service: automation.turn_on
      data:
        entity_id: group.server
    turn_off:
      service: automation.turn_off
      data:
        entity_id: group.server