platform: template
switches:

  kitchen_tv_power:
    value_template: "{{ is_state('media_player.kitchen_tv', 'on') }}"
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.power
    turn_off:
      service: switch.turn_on
      data:
        entity_id: switch.power

  vacuum_hall:
    friendly_name: 'Прихожая'
    icon_template: mdi:door-closed
    value_template: "{{ is_state('input_boolean.vacuum_hall', 'on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_hall
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_hall

  vacuum_kitchen:
    friendly_name: 'Кухня'
    icon_template: mdi:silverware-fork-knife
    value_template: "{{ is_state('input_boolean.vacuum_kitchen', 'on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_kitchen
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_kitchen

  vacuum_kidsroom:
    friendly_name: 'Детская'
    icon_template: mdi:baby-carriage
    value_template: "{{ is_state('input_boolean.vacuum_kidsroom', 'on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_kidsroom
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_kidsroom

  vacuum_livingroom:
    friendly_name: 'Гостиная'
    icon_template: mdi:sofa
    value_template: "{{ is_state('input_boolean.vacuum_livingroom', 'on') }}"
    turn_on:
      service: input_boolean.turn_on
      data:
        entity_id: input_boolean.vacuum_livingroom
    turn_off:
      service: input_boolean.turn_off
      data:
        entity_id: input_boolean.vacuum_livingroom