homekit:
  auto_start: false
  filter:
    include_entities:
      # основное
      - binary_sensor.0x00158d0001b14504
      # гостиная
      - switch.0x00158d0001715c96_switch_right
      - cover.livingroom_curtain_cover
      - binary_sensor.0x00158d0001db8a6a
  entity_config:
    # гостиная
    switch.0x00158d0001715c96_switch_right:
      name: Светильники
    binary_sensor.0x00158d0001db8a6a:
      name: Датчик дыма
      linked_battery_sensor: sensor.livingroom_smoke_battery

automation:
  - alias: "homekit_start"
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay: 00:05
      - service: homekit.start
