homekit:
  auto_start: false
  filter:
    include_entities:
    # основное
    - switch.server
    - binary_sensor.0x00158d0001b14504
    - sensor.0x00158d0001b8d3ca_temperature
    - sensor.0x00158d0001b8d3ca_humidity
    # кухня
    - switch.0x00158d00019ccab8_switch
    - sensor.kitchensensor_humidity
    - sensor.kitchensensor_temperature
    - light.kitchen_rgb_lightstrip
    - switch.kitchen_automations
    - media_player.kitchen_tv_universal
    # детская
    - switch.0x00158d0002235b38_switch_right
    - switch.0x00158d0002235b38_switch_left
    - light.kidsroom_ceiling_light_ambilight
    - light.kidsroom_nightlight
    # гостиная
    - light.livingroom_light
    - switch.0x00158d0001715c96_switch_right
    - light.livingroom_ceiling_light_ambilight
    - light.livingroom_ceiling_light_nightlight
    - cover.livingroom_curtain_cover
    - binary_sensor.0x00158d0001db8a6a
    - media_player.livingroom_tv
    # ванная
    - binary_sensor.0x00158d0001bb87d2
    # спальня
    - light.bedroom_daylight
    - light.bedroom_nightlight
  entity_config:
    sensor.0x00158d0001b8d3ca_temperature:
      name: Температура
      low_battery_threshold: 20
      linked_battery_sensor: sensor.hall_sensor_battery
    sensor.0x00158d0001b8d3ca_humidity:
      name: Влажность
      low_battery_threshold: 20
      linked_battery_sensor: sensor.hall_sensor_battery
    binary_sensor.0x00158d0001bb87d2:
      name: Датчик протечки
      linked_battery_sensor: sensor.bathroom_water_leak_battery
      low_battery_threshold: 20
    # кухня
    switch.0x00158d00019ccab8_switch:
      name: Свет
    switch.kitchen_automations:
      name: Автоматизации
    # детская
    switch.0x00158d0002235b38_switch_right:
      name: Свет
    switch.0x00158d0002235b38_switch_left:
      name: Светильники
    light.kidsroom_nightlight:
      name: Ночник
    # гостиная
    light.livingroom_light:
      name: Свет
    light.livingroom_ceiling_light_nightlight:
      name: Ночник
    switch.0x00158d0001715c96_switch_right:
      name: Светильники
    light.livingroom_ceiling_light_ambilight:
      name: Фоновый свет
    binary_sensor.0x00158d0001db8a6a:
      name: Датчик дыма
      linked_battery_sensor: sensor.livingroom_smoke_battery
    media_player.kitchen_tv_universal:
      name: Телевизор
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute
    media_player.livingroom_tv:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute

automation:
  - alias: 'homekit_start'
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay: 00:03
      - service: homekit.start