homekit:
  auto_start: false
  filter:
    include_entities:
      # основное
      - binary_sensor.0x00158d0001b14504
      - sensor.0x00158d0001b8d3ca_temperature
      - sensor.0x00158d0001b8d3ca_humidity
      # гостиная
      - switch.0x00158d0001715c96_switch_right
      - cover.livingroom_curtain_cover
      - binary_sensor.0x00158d0001db8a6a
      - media_player.livingroom_tv
      # спальня
      - light.bedroom_daylight
      - light.bedroom_nightlight
  entity_config:
    sensor.0x00158d0001b8d3ca_temperature:
      name: Температура
      low_battery_threshold: 20
      linked_battery_sensor: sensor.hall_sensor_battery
    sensor.0x00158d0001b8d3ca_humidity:
      name: Влажность
      low_battery_threshold: 20
      linked_battery_sensor: sensor.hall_sensor_battery
    # гостиная
    switch.0x00158d0001715c96_switch_right:
      name: Светильники
    binary_sensor.0x00158d0001db8a6a:
      name: Датчик дыма
      linked_battery_sensor: sensor.livingroom_smoke_battery
    media_player.livingroom_tv:
      feature_list:
        - feature: on_off
        - feature: play_pause
        - feature: play_stop
        - feature: toggle_mute

automation:
  - alias: "homekit_start"
    trigger:
      platform: homeassistant
      event: start
    action:
      - delay: 00:05
      - service: homekit.start
