yeelight:
  devices:
    10.0.0.243:
      name: kidsroom_ceiling_light
      nightlight_switch_type: light
      model: ceiling4
      use_music_mode: false
      save_on_change: false

homekit:
  filter:
    include_entities:
      - light.kidsroom_ceiling_light
      - light.kidsroom_ceiling_light_ambilight
      - light.kidsroom_ceiling_light_nightlight
  entity_config:
    light.kidsroom_ceiling_light:
      name: Свет
    light.kidsroom_ceiling_light_ambilight:
      name: Фоновый свет
    light.kidsroom_ceiling_light_nightlight:
      name: Ночник
