yeelight:
  devices:
    10.0.0.243:
      name: kidsroom_ceiling_light
      nightlight_switch_type: light
      model: ceiling4
      use_music_mode: false
      save_on_change: false

homeassistant:
  customize:
    light.kidsroom_ceiling_light:
      friendly_name: "Свет в детской"
    light.kidsroom_ceiling_light_ambilight:
      friendly_name: "Фоновый свет в детской"
    light.kidsroom_ceiling_light_nightlight:
      friendly_name: "Ночник в детской"
    switch.0x00158d0002235b38_switch_left:
      friendly_name: "Светильники в детской"

homekit:
  filter:
    include_entities:
      - light.kidsroom_ceiling_light
      - light.kidsroom_ceiling_light_ambilight
      - light.kidsroom_ceiling_light_nightlight
      - switch.0x00158d0002235b38_switch_left
  entity_config:
    light.kidsroom_ceiling_light:
      name: Свет
    light.kidsroom_ceiling_light_ambilight:
      name: Фоновый свет
    light.kidsroom_ceiling_light_nightlight:
      name: Ночник
    switch.0x00158d0002235b38_switch_left:
      name: Светильники
