homeassistant:
  customize:
    switch.0x00158d00019ccab8_switch:
      friendly_name: "Свет на кухне"
      icon: mdi:ceiling-light
    binary_sensor.kitchen_motion_occupancy:
      friendly_name: "Движение у раковины"
    sensor.kitchen_motion_illuminance:
      friendly_name: "Освещенность у раковины"
    binary_sensor.kitchen_motion2_occupancy:
      friendly_name: "Движение на кухне"
    sensor.kitchen_motion2_illuminance:
      friendly_name: "Освещенность на кухне"

switch:
  platform: template
  switches:
    kitchen_automations:
      friendly_name: "Автоматизации на кухне"
      value_template: "{{ is_state('group.kitchen_automations', 'on') }}"
      turn_on:
        service: automation.turn_on
        data:
          entity_id: group.kitchen_automations
      turn_off:
        service: automation.turn_off
        data:
          entity_id: group.kitchen_automations

homekit:
  filter:
    include_entities:
      - switch.0x00158d00019ccab8_switch
      - switch.kitchen_automations
  entity_config:
    switch.0x00158d00019ccab8_switch:
      name: Свет
    switch.kitchen_automations:
      name: Автоматизации

automation:
  - alias: "kitchen_light_on"
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: "on"
    condition:
      - condition: state
        entity_id: switch.0x00158d00019ccab8_switch
        state: "off"
      - condition: state
        entity_id: group.person
        state: "home"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "-01:00:00"
          - condition: and
            conditions:
              - condition: sun
                after: sunrise
                after_offset: "+01:00:00"
              - condition: or
                conditions:
                  - condition: state
                    entity_id: weather.dark_sky
                    state: "cloudy"
                  - condition: state
                    entity_id: weather.dark_sky
                    state: "snowy"
    action:
      service: switch.turn_on
      entity_id: switch.0x00158d00019ccab8_switch

  - alias: "kitchen_light_off"
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: "off"
      for: "00:03:10"
    action:
      - service: switch.turn_off
        entity_id: switch.0x00158d00019ccab8_switch

group:
  kitchen_motion:
    name: "Движение на кухне"
    icon: mdi:walk
    entities:
      - binary_sensor.kitchen_motion_occupancy
      - binary_sensor.kitchen_motion2_occupancy

  kitchen_automations:
    name: "Автоматизации на кухне"
    entities:
      - automation.kitchen_light_on
