weather:
  platform: darksky
  api_key: !secret dark_sky_api_key

binary_sensor:
  - platform: template
    sensors:
      cloudy:
        friendly_name: "Облачно"
        entity_id: weather.dark_sky
        value_template: "{{ is_state('weather.dark_sky', 'cloudy') or is_state('weather.dark_sky', 'rainy') or is_state('weather.dark_sky', 'snowy')}}"

homeassistant:
  customize:
    switch.0x00158d00019ccab8_switch:
      friendly_name: "Свет на кухне"
      icon: mdi:ceiling-light
    binary_sensor.kitchen_motion_occupancy:
      friendly_name: "Движение у раковины"
    sensor.kitchen_motion_illuminance:
      friendly_name: "Освещенность у раковины"
    binary_sensor.kitchen_motion2_occupancy:
      friendly_name: "Движение на кухне"
    sensor.kitchen_motion2_illuminance:
      friendly_name: "Освещенность на кухне"

automation:
  - alias: "kitchen_light_on"
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: "on"
    condition:
      - condition: state
        entity_id: switch.0x00158d00019ccab8_switch
        state: "off"
      - condition: state
        entity_id: group.person
        state: "home"
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: "-01:00:00"
          - condition: state
            entity_id: binary_sensor.cloudy
            state: "on"
    action:
      service: switch.turn_on
      entity_id: switch.0x00158d00019ccab8_switch

  - alias: "kitchen_light_off"
    trigger:
      platform: state
      entity_id: group.kitchen_motion
      to: "off"
      for: "00:03:10"
    action:
      - service: switch.turn_off
        entity_id: switch.0x00158d00019ccab8_switch

group:
  kitchen_motion:
    name: "Движение на кухне"
    icon: mdi:walk
    entities:
      - binary_sensor.kitchen_motion_occupancy
      - binary_sensor.kitchen_motion2_occupancy

  kitchen_automations:
    name: "Автоматизации на кухне"
    entities:
      - automation.kitchen_light_on
      - automation.kitchen_light_off
