webostv:
  host: 10.0.0.162
  name: livingroom_tv
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webost_tv_mac
  customize:
    sources:
      - Plex
      - YouTube
      - Apple TV

sensor:
  - platform: template
    sensors:
      livingroom_tv_source:
        friendly_name: "Источник для телевизора в гостиной"
        value_template: "{{ state_attr('media_player.livingroom_tv', 'source') }}"

automation:
  - alias: "livingroom_tv_turn_off_when_plex_pause"
    trigger:
      platform: state
      entity_id: media_player.plex_lg_oled55b7v_z
      to: "paused"
      for: "00:15:00"
    condition:
      condition: state
      entity_id: sensor.livingroom_tv_source
      state: "Plex"
    action:
      service: media_player.turn_off
      entity_id: media_player.livingroom_tv

  - alias: "livingroom_tv_switch_source_to_plex"
    trigger:
      - platform: state
        entity_id: switch.server
        to: "on"
      - platform: state
        entity_id: media_player.livingroom_tv
        to: "on"
        from: "off"
    condition:
      - condition: state
        entity_id: media_player.livingroom_tv
        state: "on"
      - condition: template
        value_template: "{{ states('sensor.livingroom_tv_source') != 'Plex' }}"
      - condition: template
        value_template: "{{ (as_timestamp(utcnow()) - as_timestamp(states.media_player.livingroom_tv.last_changed)) < 120 }}"
    action:
      service: media_player.select_source
      data:
        entity_id: media_player.livingroom_tv
        source: Plex
