influxdb:
  host: 10.0.0.62
  include:
    entities:
      - sensor.0x00158d0001b8d3ca_humidity
      - sensor.0x00158d0001b8d3ca_temperature
      - sensor.0x00158d0001700c18_humidity
      - sensor.0x00158d0001700c18_temperature
      - sensor.0x00158d0002b518b9_humidity
      - sensor.0x00158d0002b518b9_temperature

homeassistant:
  customize:
    sensor.0x00158d0001b8d3ca_humidity:
      friendly_name: "Влажность в прихожей"
    sensor.0x00158d0001b8d3ca_temperature:
      friendly_name: "Температура в прихожей"
    sensor.0x00158d0001700c18_humidity:
      friendly_name: "Влажность в детской"
    sensor.0x00158d0001700c18_temperature:
      friendly_name: "Температура в детской"
    sensor.0x00158d0002b518b9_humidity:
      friendly_name: "Влажность в гостиной"
    sensor.0x00158d0002b518b9_temperature:
      friendly_name: "Температура в гостиной"

homekit:
  filter:
    include_entities:
      - sensor.0x00158d0001700c18_humidity
      - sensor.0x00158d0001700c18_temperature
  entity_config:
    sensor.0x00158d0001700c18_humidity:
      name: Влажность
      low_battery_threshold: 30
      linked_battery_sensor: sensor.kidsroom_sensor_battery
    sensor.0x00158d0001700c18_temperature:
      name: Температура
      low_battery_threshold: 30
      linked_battery_sensor: sensor.kidsroom_sensor_battery
