sensor:
  - platform: mqtt
    name: "zigbee_coordinator_version"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.coordinator.meta.revision }}"
    icon: mdi:chip
  - platform: mqtt
    name: "zigbee2mqtt_bridge_state"
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  - platform: mqtt
    name: "zigbee2mqtt_version"
    state_topic: "zigbee2mqtt/bridge/config"
    value_template: "{{ value_json.version }}"
    icon: mdi:zigbee

switch:
  - platform: mqtt
    name: "zigbee2mqtt_permit_join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

timer:
  zigbee2mqtt_permit_join:
    name: "Таймер подключения zigbee-устройств"
    duration: 600

automation:
  - alias: "zigbee_join_enabled"
    trigger:
      platform: state
      entity_id: switch.zigbee2mqtt_permit_join
      to: "on"
    action:
      service: timer.start
      entity_id: timer.zigbee2mqtt_permit_join
  - alias: "zigbee_join_disabled"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.zigbee_permit_join
      - platform: state
        entity_id: switch.zigbee2mqtt_permit_join
        to: "off"
    action:
      - service: timer.cancel
        data:
          entity_id: timer.zigbee2mqtt_permit_join
      - service: switch.turn_off
        entity_id: switch.zigbee2mqtt_permit_join
