type: glance
title: "Детская"
entities:
  - entity: light.kidsroom_ceiling_light
    name: "Свет"
    icon: mdi:ceiling-light
    tap_action:
      action: toggle
  - entity: light.kidsroom_ceiling_light_nightlight
    name: "Ночник"
    tap_action:
      action: toggle
  - entity: switch.kidsroom_switch_switch_left
    name: "Светильники"
    icon: mdi:track-light
    tap_action:
      action: toggle
