livingroom_tv_eat:
  name: Есть и пить можно только на кухне!
  entity_id: input_boolean.notify_livingroom_tv_eat
  state: "on"
  repeat: 1
  can_acknowledge: true
  skip_first: false
  notifiers:
    - livingroom_tv_eat
