# гостиная
cover.livingroom_curtain_cover:
  friendly_name: "Шторы"
binary_sensor.0x00158d0001db8a6a:
  friendly_name: "Датчик дыма"
sensor.livingroom_smoke_battery:
  friendly_name: "Датчик дыма"
vacuum.rockrobo:
  friendly_name: "Пылесос"
media_player.livingroom_tv:
  friendly_name: "Телевизор"
  device_class: tv
media_player.apple_tv_4:
  friendly_name: "Apple TV"

switch.socket_switch:
  friendly_name: "Розетка"
  icon: mdi:power-socket-au
sensor.socket_power:
  friendly_name: "Розетка"

device_tracker.iphonerosthome:
  friendly_name: "iPhone Рост"
device_tracker.iphonejanahome:
  friendly_name: "iPhone Яна"

person.rostislav:
  friendly_name: "Рост"
person.iana:
  friendly_name: "Яна"
person.nina:
  friendly_name: "Бабушка"
