# прихожая
sensor.hall_sensor_battery:
  friendly_name: 'Датчик температуры и влажности'
sensor.0x00158d0001b8d3ca_temperature:
  friendly_name: 'Прихожая Температура'
sensor.0x00158d0001b8d3ca_humidity:
  friendly_name: 'Прихожая Влажность'
binary_sensor.0x00158d0001b14504:
  friendly_name: 'Прихожая Дверь'
sensor.hall_door_battery:
  friendly_name: 'Прихожая Дверь'
light.yeelight_white_34ce00882e95:
  friendly_name: 'Верхний свет'

# кухня
sensor.kitchen_sensor_battery:
  friendly_name: 'Датчик температуры и влажности'
sensor.0x00158d0001700c18_temperature:
  friendly_name: 'Температура'
sensor.0x00158d0001700c18_humidity:
  friendly_name: 'Влажность'
sensor.0x00158d0001a24e62_illuminance:
  hidden: true
  friendly_name: 'Освещенность'
binary_sensor.0x00158d0001a24e62_occupancy:
  hidden: true
  friendly_name: 'Движение на кухне'
sensor.0x00158d0002236dfb_illuminance:
  hidden: true
  friendly_name: 'Освещенность у раковины'
binary_sensor.0x00158d0002236dfb_occupancy:
  hidden: true
  friendly_name: 'Движение у раковины'
binary_sensor.kitchen_motion_sensor:
  friendly_name: 'Движение'
light.kitchen_rgb_lightstrip:
  friendly_name: 'Ночник на кухне'
switch.0x00158d00019ccab8_switch:
  friendly_name: 'Свет'
  icon: mdi:ceiling-light
media_player.kitchen_tv_universal:
  friendly_name: 'Телевизор на кухне'

# кухня телевизор
script.smart_hub:
  friendly_name: 'Smart Hub'
  icon: mdi:cube
script.select:
  friendly_name: 'Select'
  icon: mdi:radiobox-blank
script.left:
  friendly_name: 'Left'
  icon: mdi:arrow-left-bold
script.right:
  friendly_name: 'Right'
  icon: mdi:arrow-right-bold

# детская
binary_sensor.0x00158d0001e42e65_contact:
  friendly_name: 'Дверь в детскую'
switch.0x00158d0002235b38_switch_right:
  friendly_name: 'Выключатель'
  icon: mdi:light-switch
switch.0x00158d0002235b38_switch_left:
  friendly_name: 'Светильники'
  icon: mdi:track-light
light.kidsroom_ceiling_light:
  friendly_name: 'Свет'
  icon: mdi:ceiling-light
light.kidsroom_ceiling_light_ambilight:
  friendly_name: 'Фоновый свет'
light.kidsroom_nightlight:
  friendly_name: 'Ночник в детской'
  icon: mdi:lamp
sensor.0x00158d0001e42e65_battery:
  friendly_name: 'Датчик двери'

# гостиная
sensor.livingroom_sensor_battery:
  friendly_name: 'Датчик температуры и влажности'
switch.0x00158d0001715c96_switch_left:
  friendly_name: 'Выключатель'
  icon: mdi:light-switch
light.livingroom_ceiling_light:
  friendly_name: 'Свет'
  icon: mdi:ceiling-light
light.livingroom_nightlight:
  friendly_name: 'Ночник'
  icon: mdi:lamp
switch.0x00158d0001715c96_switch_right:
  friendly_name: 'Светильники'
  icon: mdi:track-light
cover.0x00158d0001ef4b95_cover:
  friendly_name: 'Шторы'
binary_sensor.0x00158d0001db8a6a:
  friendly_name: 'Датчик дыма'
sensor.livingroom_smoke_battery:
  friendly_name: 'Датчик дыма'
binary_sensor.cube_158d00010ed5cf:
  friendly_name: 'Куб'
  icon: mdi:cube-outline
vacuum.xiaomi_vacuum_cleaner:
  friendly_name: 'Пылесос'
  icon: mdi:roomba
binary_sensor.0x00158d0001ab1e55:
  friendly_name: 'Гостинная Дверь'
sensor.livingroom_door_battery:
  friendly_name: 'Гостинная Дверь'
media_player.livingroom_tv:
  friendly_name: 'Телевизор'
  device_class: tv
media_player.apple_tv_4:
  friendly_name: 'Apple TV'
plant.crassula:
  friendly_name: 'Денежное дерево'

# ванная
binary_sensor.0x00158d0001bb87d2:
  friendly_name: 'Датчик протечки'
sensor.bathroom_water_leak_battery:
  friendly_name: 'Датчик протечки'

# спальня
light.bedroom_daylight:
  friendly_name: 'Свет'
light.bedroom_nightlight:
  friendly_name: 'Ночник'
sensor.bedroom_button_battery:
  friendly_name: 'Кнопка'
sensor.bedroom_switch_battery:
  friendly_name: 'Выключатель'

# сервер
switch.server:
  friendly_name: 'Сервер'
switch.transmission:
  friendly_name: 'Ограничение скорости'
  icon: mdi:speedometer

switch.socket_switch:
  friendly_name: 'Розетка'
  icon: mdi:power-socket-au
sensor.socket_power:
  friendly_name: 'Розетка'

device_tracker.iphonerosthome:
  friendly_name: 'iPhone Рост'
device_tracker.iphonejanahome:
  friendly_name: 'iPhone Яна'

person.rostislav:
  friendly_name: 'Рост'
person.jana:
  friendly_name: 'Яна'
