# прихожая
sensor.hall_sensor_battery:
  friendly_name: "Датчик температуры и влажности"
sensor.0x00158d0001b8d3ca_temperature:
  friendly_name: "Прихожая Температура"
sensor.0x00158d0001b8d3ca_humidity:
  friendly_name: "Прихожая Влажность"

# кухня
sensor.kitchen_motion2_illuminance:
  hidden: true
  friendly_name: "Освещенность"
binary_sensor.kitchen_motion2_occupancy:
  hidden: true
  friendly_name: "Движение на кухне"
sensor.kitchen_motion_illuminance:
  hidden: true
  friendly_name: "Освещенность у раковины"
binary_sensor.kitchen_motion_occupancy:
  hidden: true
  friendly_name: "Движение у раковины"
binary_sensor.kitchen_motion_sensor:
  friendly_name: "Движение"
light.kitchen_rgb_lightstrip:
  friendly_name: "Ночник на кухне"
switch.0x00158d00019ccab8_switch:
  friendly_name: "Свет на кухне"
  icon: mdi:ceiling-light

# кухня телевизор
script.smart_hub:
  friendly_name: "Smart Hub"
  icon: mdi:cube
script.select:
  friendly_name: "Select"
  icon: mdi:radiobox-blank
script.left:
  friendly_name: "Left"
  icon: mdi:arrow-left-bold
script.right:
  friendly_name: "Right"
  icon: mdi:arrow-right-bold

# детская
sensor.kitchen_sensor_battery:
  friendly_name: "Датчик температуры и влажности"
sensor.0x00158d0001700c18_temperature:
  friendly_name: "Температура"
sensor.0x00158d0001700c18_humidity:
  friendly_name: "Влажность"

# гостиная
sensor.livingroom_sensor_battery:
  friendly_name: "Датчик температуры и влажности"
cover.livingroom_curtain_cover:
  friendly_name: "Шторы"
binary_sensor.0x00158d0001db8a6a:
  friendly_name: "Датчик дыма"
sensor.livingroom_smoke_battery:
  friendly_name: "Датчик дыма"
binary_sensor.cube_158d00010ed5cf:
  friendly_name: "Куб"
  icon: mdi:cube-outline
vacuum.rockrobo:
  friendly_name: "Пылесос"
media_player.livingroom_tv:
  friendly_name: "Телевизор"
  device_class: tv
media_player.apple_tv_4:
  friendly_name: "Apple TV"
plant.crassula:
  friendly_name: "Денежное дерево"

# сервер
switch.server:
  friendly_name: "Сервер"

switch.socket_switch:
  friendly_name: "Розетка"
  icon: mdi:power-socket-au
sensor.socket_power:
  friendly_name: "Розетка"

device_tracker.iphonerosthome:
  friendly_name: "iPhone Рост"
device_tracker.iphonejanahome:
  friendly_name: "iPhone Яна"

person.rostislav:
  friendly_name: "Рост"
person.iana:
  friendly_name: "Яна"
person.nina:
  friendly_name: "Бабушка"
