hall:
  name: 'Прихожая'
  entities:
    - sensor.0x00158d0001b8d3ca_temperature
    - sensor.0x00158d0001b8d3ca_humidity
    - binary_sensor.0x00158d0001b14504
    - light.yeelight_white_34ce00882e95

kitchen:
  name: 'Кухня'
  entities:
    - sensor.kitchensensor_temperature
    - sensor.kitchensensor_humidity
    - sensor.illumination_34ce00fb7404
    - binary_sensor.kitchen_motion_sensor
    - light.kitchen_rgb_lightstrip
    - light.gateway_light_34ce00fb7404
    - media_player.kitchen_ue32f6510

kitchen_tv:
  name: 'Телевизор на кухне'
  control: hidden
  entities:
    - switch.kitchen_tv_power
    - script.smart_hub
    - script.select
    - script.left
    - script.right

livingroom:
  name: 'Гостиная'
  entities:
    - light.livingroom_ceiling_light
    - light.livingroom_nightlight
    - binary_sensor.0x00158d0001db8a6a
    - vacuum.xiaomi_vacuum_cleaner
    - binary_sensor.cube_158d00010ed5cf
    - binary_sensor.0x00158d0001ab1e55

bathroom:
  name: 'Ванная'
  entities:
    - binary_sensor.0x00158d0001bb87d2

bedroom_light:
  name: 'Спальня Свет'
  entities:
    - light.bedroom_color
    - light.bedroom_mono

person:
  entities:
    - person.rostislav
    - person.iana

kitchen_automations:
  name: 'Автоматизации на кухне'
  entities:
    - automation.kitchen_light_on
    - automation.kitchen_light_off
    - automation.kitchen_nightlight_on
    - automation.kitchen_nightlight_off

kitchen_motion_sensor:
  name: 'Движение'
  icon: mdi:walk
  entities:
    - binary_sensor.0x00158d0002236dfb_occupancy
    - binary_sensor.0x00158d0001a24e62_occupancy

server:
  name: 'Автоматическое включение/выключение'
  entities:
    - automation.server_turn_off
    - automation.server_turn_on_when_tv_on
    - automation.server_turn_on_when_someone_comes