hall:
  name: 'Прихожая'
  entities:
    - sensor.0x00158d0001b8d3ca_temperature
    - sensor.0x00158d0001b8d3ca_humidity
    - binary_sensor.0x00158d0001b14504
    - light.yeelight_white_34ce00882e95

kitchen_tv:
  name: 'Телевизор на кухне'
  entities:
    - switch.kitchen_tv_power
    - script.smart_hub
    - script.select
    - script.left
    - script.right

bathroom:
  name: 'Ванная'
  entities:
    - binary_sensor.0x00158d0001bb87d2

bedroom_light:
  name: 'Группа ламп в спальне'
  entities:
    - light.bedroom_color
    - light.bedroom_mono

person:
  entities:
    - person.rostislav
    - person.iana
    - person.nina