filter:
  include_entities:
   # основное
   - switch.server
   - binary_sensor.0x00158d0001b14504
   - sensor.0x00158d0001b8d3ca_temperature
   - sensor.0x00158d0001b8d3ca_humidity
   # кухня
   - switch.0x00158d00019ccab8_switch
   - sensor.kitchensensor_humidity
   - sensor.kitchensensor_temperature
   - light.kitchen_rgb_lightstrip
   - switch.kitchen_automations_light
   - switch.kitchen_automations_nightlight
   # детская
   - switch.wall_switch_right_158d0002235b38
   - switch.wall_switch_left_158d0002235b38
   - light.kidsroom_ceiling_light_ambilight
   # гостиная
   - switch.0x00158d0001715c96_switch_left
   - switch.0x00158d0001715c96_switch_right
   - light.livingroom_nightlight
   - cover.0x00158d0001ef4b95_cover
   - binary_sensor.0x00158d0001db8a6a
   - media_player.livingroom_tv
   # ванная
   - binary_sensor.0x00158d0001bb87d2
   # спальня
   - light.bedroom_daylight
   - light.bedroom_nightlight
entity_config:
  sensor.0x00158d0001b8d3ca_temperature:
    name: Температура
    low_battery_threshold: 5
    linked_battery_sensor: sensor.hall_sensor_battery
  sensor.0x00158d0001b8d3ca_humidity:
    name: Влажность
    low_battery_threshold: 5
    linked_battery_sensor: sensor.hall_sensor_battery
  switch.wall_switch_right_158d0002235b38:
    name: Свет
  switch.wall_switch_left_158d0002235b38:
    name: Светильники
  binary_sensor.0x00158d0001db8a6a:
    name: Датчик дыма
    linked_battery_sensor: sensor.livingroom_smoke_battery
  binary_sensor.0x00158d0001bb87d2:
    name: Датчик протечки
    linked_battery_sensor: sensor.bathroom_water_leak_battery
    low_battery_threshold: 5
  media_player.livingroom_tv:
    feature_list:
      - feature: on_off
      - feature: play_pause
      - feature: play_stop
      - feature: toggle_mute