broker: '10.0.0.62'
port: 1883
client_id: homeassistant
username: !secret mqtt_username
password: !secret mqtt_password
discovery: true
birth_message:
  topic: 'hass/status'
  payload: 'online'
will_message:
  topic: 'hass/status'
  payload: 'offline'