- platform: webostv
  host: 10.0.0.162
  name: livingroom_tv
  filename: webostv.conf
- name: livingroom_tv_eat
  platform: group
  services:
    - service: livingroom_tv
      data:
        message: 'Есть и пить можно только на кухне!'
        data:
          icon: '/config/images/do_not_eat.png'
- name: bathroom_water_leak
  platform: group
  services:
    - service: livingroom_tv
      data:
        message: 'Обнаружена протечка воды в ванной!'
        data:
          icon: '/config/images/water_leak.png'
- name: transmission_downloaded_torrent
  platform: group
  services:
    - service: livingroom_tv
      data:
        message: 'Скачивание завершено'