- name: rostislav
  id: rostislav
  device_trackers:
    - device_tracker.rost_watch
    - device_tracker.rost_phone
    - device_tracker.rost_laptop
- name: jana
  id: jana
  device_trackers:
    - device_tracker.jana_phone
    - device_tracker.jana_laptop
- name: nina
  id: nina
  device_trackers:
    - device_tracker.nina_phone