- name: rostislav
  id: rostislav
  user_id: 7c6ea3df58824829b8febfaede0223d8
  device_trackers:
    - device_tracker.rost_watch
    - device_tracker.rost_phone
    - device_tracker.rost_laptop
    - device_tracker.iphone
- name: jana
  id: jana
  user_id: 3ee3843636544399a445855ea06ea724
  device_trackers:
    - device_tracker.jana_phone
    - device_tracker.jana_laptop
    - device_tracker.iphone_2
- name: nina
  id: nina
  device_trackers:
    - device_tracker.nina_phone