crassula:
  sensors:
    moisture: sensor.mi_flora_moisture
    battery: sensor.mi_flora_battery
    temperature: sensor.mi_flora_temperature
    conductivity: sensor.mi_flora_conductivity
    brightness: sensor.mi_flora_light_intensity