db_url: mysql://home_assistant:home_assistant@10.0.0.62/home_assistant?charset=utf8
purge_keep_days: 7
exclude:
  domains:
    - automation
    - group
    - script
  entities:
    - sensor.transmission_active_torrents
    - sensor.transmission_completed_torrents
    - sensor.transmission_down_speed
    - sensor.transmission_paused_torrents
    - sensor.transmission_started_torrents
    - sensor.transmission_total_torrents
    - sensor.transmission_up_speed