smart_hub:
  sequence:
    - service: switch.turn_on
      entity_id: switch.smart_hub

select:
  sequence:
    - service: switch.turn_on
      entity_id: switch.select

left:
  sequence:
    - service: switch.turn_on
      entity_id: switch.left

right:
  sequence:
    - service: switch.turn_on
      entity_id: switch.right

vacuum_zoned_cleanup:
  sequence:
    - service: vacuum.send_command
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_zoned_clean
        params: >
          [
          {%- set comma = joiner(',') -%}
          {%- set repeats = states('input_number.vacuum_cleaning_repeats')|int -%}
          {%- if is_state('input_boolean.vacuum_hall', 'on') -%}
            {{ comma() }}[28161, 22317, 30561, 25317, {{ repeats }}]
          {%- endif -%}
          {%- if is_state('input_boolean.vacuum_kitchen', 'on') -%}
            {{ comma() }}[22124, 29187, 26074, 30937, {{ repeats }}]
          {%- endif -%}
          {%- if is_state('input_boolean.vacuum_kidsroom', 'on') -%}
            {{ comma() }}[23219, 26493, 27119, 28993, {{ repeats }}]
          {%- endif -%}
          {%- if is_state('input_boolean.vacuum_livingroom', 'on') -%}
            {{ comma() }}[22127, 22835, 27127, 25135, {{ repeats }}]
          {%- endif -%}
          ]

aqara_switch_set_operation_mode:
  description: 'Настройка режима работы проводного выключателя Aqara'
  fields:
    switch_id:
      description: 'Идентификатор выключателя'
      example: '0x00158d0001715c96'
    button:
      description: 'Клавиша'
      example: 'single | left | right'
    operation_mode:
      description: 'Режим работы'
      example: 'control_left_relay | control_right_relay | decoupled'
  sequence:
    - service: mqtt.publish
      data_template:
        topic: "zigbee2mqtt/{{ switch_id }}/system/set"
        payload: >-
          {
            "operation_mode": {
              "button": "{{ button }}",
              "state": "{{ operation_mode }}"
            }
          }
    - service: mqtt.publish
      data:
        topic: "zigbee2mqtt/{{ switch_id }}/system/get"
        payload: >-
          {
            "operation_mode": {
              "button": "left"
            }
          }