host: 10.0.0.213
port: 9091
username: !secret transmission_username
password: !secret transmission_password
turtle_mode: true
monitored_conditions:
  - current_status
  - download_speed
  - upload_speed
  - active_torrents
  - paused_torrents
  - total_torrents
  - started_torrents
  - completed_torrents