devices:
  10.0.0.127:
    name: bedroom_mono
    model: mono1
    use_music_mode: false
    save_on_change: false
  10.0.0.15:
    name: bedroom_color
    model: color1
    use_music_mode: false
    save_on_change: false

custom_effects:
  - name: 'Water Leak'
    flow_params:
      count: 5
      transitions:
        - RGBTransition: [0, 0, 255, 50, 0]
        - RGBTransition: [0, 0, 255, 250, 100]
        - RGBTransition: [0, 0, 255, 250, 0]
        - RGBTransition: [0, 0, 255, 250, 100]
        - RGBTransition: [0, 0, 255, 250, 0]
        - SleepTransition: [5000]