devices:
  10.0.0.127:
    name: bedroom_mono
    model: mono1
    use_music_mode: true
    save_on_change: false
  10.0.0.15:
    name: bedroom_color
    model: color1
    use_music_mode: true
    save_on_change: false
  10.0.0.152:
    name: kitchen_rgb_lightstrip
    model: strip1
    use_music_mode: true
    save_on_change: false
  10.0.0.243:
    name: kidsroom_ceiling_light
    model: ceiling4
    use_music_mode: false
    save_on_change: false
  10.0.0.137:
    name: livingroom_ceiling_light
    model: ceiling4
    use_music_mode: false
    save_on_change: false

custom_effects:
- name: 'Plex'
  flow_params:
    count: 0
    transitions:
    - RGBTransition: [225, 106, 11, 50, 1]
- name: 'Water Leak'
  flow_params:
    count: 5
    transitions:
    - RGBTransition: [0, 0, 255, 50, 0]
    - RGBTransition: [0, 0, 255, 250, 100]
    - RGBTransition: [0, 0, 255, 250, 0]
    - RGBTransition: [0, 0, 255, 250, 100]
    - RGBTransition: [0, 0, 255, 250, 0]
    - SleepTransition: [5000]