devices:
  10.0.0.127:
    name: bedroom_mono
    model: mono1
    use_music_mode: false
    save_on_change: false
  10.0.0.15:
    name: bedroom_color
    model: color1
    use_music_mode: false
    save_on_change: false
