platform: template
sensors:
  kitchen_motion_sensor_battery:
    friendly_name: 'Датчик движения'
    value_template: >
      {% if is_state('binary_sensor.motion_sensor_158d0001a24e62', 'unknown') %}
          0
      {% else %}
        {{ state_attr('binary_sensor.motion_sensor_158d0001a24e62', 'battery_level') | int }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('binary_sensor.motion_sensor_158d0001a24e62', 'battery_level') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('binary_sensor.motion_sensor_158d0001a24e62', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  kitchen_motion_sensor2_battery:
    friendly_name: 'Датчик движения у раковины'
    value_template: >
      {% if is_state('binary_sensor.motion_sensor_158d0002236dfb', 'unknown') %}
          0
      {% else %}
        {{ state_attr('binary_sensor.motion_sensor_158d0002236dfb', 'battery_level') | int }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('binary_sensor.motion_sensor_158d0002236dfb', 'battery_level') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('binary_sensor.motion_sensor_158d0002236dfb', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  livingroom_miflora_battery:
    friendly_name: 'Датчик растений'
    value_template: >
      {% if is_state('sensor.mi_flora_battery', 'unknown') %}
          0
      {% else %}
        {{ states('sensor.mi_flora_battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = states('sensor.mi_flora_battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.mi_flora_battery', 'unknown') %}
        mdi:battery-bluetooth
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}-bluetooth
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'