platform: template
sensors:
  hall_temperature_battery:
    friendly_name: 'Датчик температуры и влажности'
    value_template: >
      {% if is_state('sensor.0x00158d0001b8d3ca_temperature', 'unknown') %}
          0
      {% else %}
        {{ state_attr('sensor.0x00158d0001b8d3ca_temperature', 'battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('sensor.0x00158d0001b8d3ca_temperature', 'battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.0x00158d0001b8d3ca_temperature', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  kitchen_temperature_battery:
    friendly_name: 'Датчик температуры и влажности'
    value_template: >
      {% if is_state('sensor.0x00158d0001700c18_temperature', 'unknown') %}
          0
      {% else %}
        {{ state_attr('sensor.0x00158d0001700c18_temperature', 'battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('sensor.0x00158d0001700c18_temperature', 'battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.0x00158d0001700c18_temperature', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  kitchen_motion_sensor_battery:
    friendly_name: 'Датчик движения'
    value_template: >
      {% if is_state('binary_sensor.motion_sensor_158d0001a24e62', 'unknown') %}
          0
      {% else %}
        {{ state_attr('binary_sensor.motion_sensor_158d0001a24e62', 'battery_level') | int }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('binary_sensor.motion_sensor_158d0001a24e62', 'battery_level') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('binary_sensor.motion_sensor_158d0001a24e62', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  kitchen_motion_sensor2_battery:
    friendly_name: 'Датчик движения у раковины'
    value_template: >
      {% if is_state('binary_sensor.motion_sensor_158d0002236dfb', 'unknown') %}
          0
      {% else %}
        {{ state_attr('binary_sensor.motion_sensor_158d0002236dfb', 'battery_level') | int }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('binary_sensor.motion_sensor_158d0002236dfb', 'battery_level') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('binary_sensor.motion_sensor_158d0002236dfb', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  livingroom_temperature_battery:
    friendly_name: 'Датчик температуры и влажности'
    value_template: >
      {% if is_state('sensor.0x00158d0002b518b9_temperature', 'unknown') %}
          0
      {% else %}
        {{ state_attr('sensor.0x00158d0002b518b9_temperature', 'battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('sensor.0x00158d0002b518b9_temperature', 'battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.0x00158d0002b518b9_temperature', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  livingroom_miflora_battery:
    friendly_name: 'Датчик растений'
    value_template: >
      {% if is_state('sensor.mi_flora_battery', 'unknown') %}
          0
      {% else %}
        {{ states('sensor.mi_flora_battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = states('sensor.mi_flora_battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.mi_flora_battery', 'unknown') %}
        mdi:battery-bluetooth
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}-bluetooth
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  livingroom_smoke_battery_level:
    friendly_name: 'Датчик дыма'
    value_template: >
      {% if is_state('sensor.livingroom_smoke_battery', 'unknown') %}
          0
      {% else %}
        {{ states('sensor.livingroom_smoke_battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = states('sensor.livingroom_smoke_battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.livingroom_smoke_battery', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  bathroom_water_leak_battery_level:
    friendly_name: 'Датчик протечки'
    value_template: "{{ states('sensor.bathroom_water_leak_battery') }}"
    icon_template: >
      {% set battery_level = states('sensor.bathroom_water_leak_battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.bathroom_water_leak_battery', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  bedroom_switch_battery:
    friendly_name: 'Выключатель'
    value_template: "{{ state_attr('sensor.0x00158d0001639086', 'battery') }}"
    icon_template: >
      {% set battery_level = state_attr('sensor.0x00158d0001639086', 'battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  bedroom_button_battery:
    friendly_name: 'Кнопка'
    value_template: >
      {% if is_state('sensor.0x00158d00016445cc', 'unknown') %}
          0
      {% else %}
        {{ state_attr('sensor.0x00158d00016445cc', 'battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = state_attr('sensor.0x00158d00016445cc', 'battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.0x00158d00016445cc', 'unknown') %}
        mdi:battery
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'