- alias: 'zigbee_join_enabled'
  trigger:
    platform: state
    entity_id: switch.zigbee2mqtt_permit_join
    to: 'on'
  action:
    service: timer.start
    entity_id: timer.zigbee2mqtt_permit_join