- alias: 'flux turn on'
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_on
      entity_id: switch.flux

- id: '9'
  alias: Включение телевизора на кухне
  initial_state: 'off'
  trigger:
  - platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010ed5cf
      action_type: tap_twice
  action:
    service: script.power