- alias: 'bathroom_notify_water_leak'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alert.bathroom_water_leak
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.livingroom_ceiling_light_ambilight
      effect: 'Water Leak'