platform: universal
name: kitchen_tv_universal
children:
  - media_player.kitchen_tv
commands:
  turn_on:
    service: switch.turn_on
    data:
      entity_id: switch.samsung_tv_power
  turn_off:
    service: media_player.turn_off
    data:
      entity_id: media_player.kitchen_tv
  volume_up:
    service: media_player.volume_up
    data:
      entity_id: media_player.kitchen_tv
  volume_down:
    service: media_player.volume_down
    data:
      entity_id: media_player.kitchen_tv
  volume_mute:
    service: media_player.volume_mute
    data:
      entity_id: media_player.kitchen_tv
  volume_set:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.kitchen_tv
      volume_level: '{{ volume_level }}'
attributes:
  state: media_player.kitchen_tv
  is_volume_muted: media_player.kitchen_tv|is_volume_muted