homeassistant:
  name: Home
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 177
  unit_system: metric
  time_zone: Europe/Kirov
  customize: !include include/customize.yaml
  packages: !include_dir_named include/packages

alert: !include include/alert.yaml
automation: !include_dir_merge_list include/automations/
camera: !include include/camera.yaml
config:
device_tracker: !include_dir_list include/device_tracker/

discovery:
  ignore:
    - yeelight

frontend:
group: !include include/groups.yaml
history: !include include/history.yaml
homekit: !include include/homekit.yaml
http:
influxdb: !include include/influxdb.yaml
input_boolean: !include include/input_boolean.yaml
input_number: !include include/input_number.yaml
input_select: !include include/input_select.yaml
light: !include_dir_list include/light/
logbook:

lovelace:
  mode: yaml

media_player: !include_dir_list include/media_player/
mqtt: !include include/mqtt.yaml
notify: !include_dir_list include/notify/
person: !include include/person.yaml
plant: !include include/plant.yaml
recorder: !include include/recorder.yaml
scene: !include_dir_list include/scene/
script: !include include/scripts.yaml
stream:
sensor: !include_dir_list include/sensor/

shell_command:
  turn_off_server: 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /config/.ssh/id_rsa homeassistant@10.0.0.213 sudo pm-suspend'

sun:
system_health:
switch: !include_dir_list include/switch/
timer: !include_dir_named include/timer/
updater:
wake_on_lan:
weather: !include_dir_list include/weather/
yeelight: !include include/yeelight.yaml