homeassistant:
  name: Home
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 177
  unit_system: metric
  time_zone: Europe/Kirov
  customize: !include include/customize.yaml
  packages: !include_dir_named packages/

automation: !include_dir_merge_list include/automations/
camera: !include include/camera.yaml
config:

discovery:
  ignore:
    - yeelight

frontend:
history: !include include/history.yaml
http:
influxdb: !include include/influxdb.yaml
logbook:

lovelace:
  mode: yaml

media_player: !include_dir_list include/media_player/
mobile_app:
ios:
mqtt: !include include/mqtt.yaml
notify: !include_dir_list include/notify/
plant: !include include/plant.yaml
recorder: !include include/recorder.yaml
stream:
sensor: !include_dir_list include/sensor/
sun:
system_health:
switch: !include_dir_list include/switch/
updater:
weather: !include_dir_list include/weather/
