homeassistant:
  name: Home
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 177
  unit_system: metric
  time_zone: Europe/Kirov
  customize: !include include/customize.yaml
  packages: !include_dir_named packages/

camera: !include include/camera.yaml
config:

discovery:
  ignore:
    - yeelight

frontend:
history: !include include/history.yaml
http:
influxdb: !include include/influxdb.yaml
logbook:

lovelace:
  mode: yaml

mobile_app:
ios:

mqtt:
  broker: "10.0.0.62"
  port: 1883
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

notify: !include_dir_list include/notify/
recorder: !include include/recorder.yaml
stream:
sensor: !include_dir_list include/sensor/
sun:
system_health:
switch: !include_dir_list include/switch/
updater:

weather:
  platform: darksky
  api_key: !secret dark_sky_api_key
