title: 'Дом'
views:
  - title: 'Дом'
    icon: mdi:home
    path: home
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - entity: person.rostislav
            icon: mdi:human-male
          - entity: person.iana
            icon: mdi:human-female
      - type: vertical-stack
        cards:
          - type: picture-glance
            title: 'Подъезд'
            entities:
              - camera.entrance
            camera_image: camera.entrance
          - type: picture-glance
            title: 'Прихожая'
            entities:
              - camera.hall
              - binary_sensor.0x00158d0001b14504
            camera_image: camera.hall
      - type: glance
        title: 'Кухня'
        entities:
          - group.kitchen_motion_sensor
          - entity: switch.0x00158d00019ccab8_switch
            tap_action:
              action: toggle
          - entity: light.kitchen_rgb_lightstrip
            name: 'Ночник'
            icon: mdi:lamp
            tap_action:
              action: toggle
      - type: glance
        title: 'Детская'
        entities:
          - entity: binary_sensor.0x00158d0001e42e65_contact
            name: Дверь
          - entity: switch.0x00158d0003551125_switch_right
            name: Свет
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - entity: switch.0x00158d0003551125_switch_left
            tap_action:
              action: toggle
      - type: glance
        title: 'Гостиная'
        entities:
          - entity: binary_sensor.0x00158d0001ab1e55
            name: 'Дверь'
          - binary_sensor.0x00158d0001db8a6a
          - entity: cover.0x00158d0001ef4b95_cover
            tap_action:
              action: toggle
          - switch.0x00158d0001715c96_switch_left
          - entity: switch.0x00158d0001715c96_switch_right
            icon: mdi:track-light
            tap_action:
              action: toggle
      - type: glance
        title: 'Спальня'
        entities:
          - entity: light.bedroom_daylight
            icon: mdi:ceiling-light
            tap_action:
                action: toggle
          - entity: light.bedroom_nightlight
            icon: mdi:lamp
            tap_action:
                action: toggle

  - title: 'Погода'
    icon: mdi:weather-partly-cloudy
    path: weather
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        title: 'Солнце'
        show_header_toggle: false
        entities:
          - entity: sensor.sun_sunrise
            icon: mdi:weather-sunset-up
          - entity: sensor.sun_sunset
            icon: mdi:weather-sunset-down
      - type: history-graph
        title: 'Температура'
        entities:
          - entity: sensor.0x00158d0001b8d3ca_temperature
            name: 'Прихожая'
          - entity: sensor.0x00158d0001700c18_temperature
            name: 'Детская'
          - entity: sensor.0x00158d0002b518b9_temperature
            name: 'Гостиная'
      - type: sensor
        name: 'Давление'
        entity: sensor.0x00158d0002b518b9_pressure
        graph: line
      - type: history-graph
        title: 'Влажность'
        entities:
          - entity: sensor.0x00158d0001b8d3ca_humidity
            name: 'Прихожая'
          - entity: sensor.0x00158d0001700c18_humidity
            name: 'Детская'
          - entity: sensor.0x00158d0002b518b9_humidity
            name: 'Гостиная'

  - title: 'Кухня'
    icon: mdi:silverware-fork-knife
    path: kitchen
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: switch.0x00158d00019ccab8_switch
              - entity: light.kitchen_rgb_lightstrip
                name: 'Ночник'
              - entity: switch.kitchen_automations
                name: 'Автоматизации'
      - type: media-control
        entity: media_player.kitchen_tv_universal

  - title: 'Детская'
    icon: mdi:baby-carriage
    path: kidsroom
    cards:
      - type: entities
        entities:
          - entity: binary_sensor.0x00158d0001e42e65_contact
            name: 'Дверь'
          - entity: switch.0x00158d0002235b38_switch_right
            tap_action:
              action: toggle
          - entity: light.kidsroom_ceiling_light
            tap_action:
              action: toggle
          - entity: light.kidsroom_ceiling_light_ambilight
          - entity: light.kidsroom_nightlight
            name: Ночник
            tap_action:
              action: toggle
          - entity: switch.0x00158d0002235b38_switch_left
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
        - type: sensor
          entity: sensor.0x00158d0001700c18_temperature
          name: 'Температура'
          graph: line
        - type: sensor
          entity: sensor.0x00158d0001700c18_humidity
          name: 'Влажность'
          graph: line

  - title: 'Гостиная'
    icon: mdi:sofa
    path: livingroom
    cards:
      - type: entities
        entities:
          - switch.0x00158d0001715c96_switch_left
          - entity: light.livingroom_light
            name: 'Свет'
            icon: mdi:ceiling-light
          - entity: light.livingroom_nightlight
            name: 'Ночник'
          - entity: light.livingroom_ceiling_light_ambilight
            name: 'Фоновый свет'
            icon: mdi:lightbulb-on
          - switch.0x00158d0001715c96_switch_right
          - cover.0x00158d0001ef4b95_cover
      - type: media-control
        entity: media_player.livingroom_tv
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.0x00158d0002b518b9_temperature
            name: 'Температура'
            graph: line
          - type: sensor
            entity: sensor.0x00158d0002b518b9_humidity
            name: 'Влажность'
            graph: line
      - type: plant-status
        entity: plant.crassula

  - title: 'Спальня'
    icon: mdi:bed-empty
    path: bedroom
    cards:
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: light.bedroom_daylight
            icon: mdi:ceiling-light
            tap_action:
              action: toggle
          - type: entity-button
            entity: light.bedroom_nightlight
            icon: mdi:lamp
            tap_action:
              action: toggle

  - title: 'Пылесос'
    icon: mdi:robot-vacuum
    path: vacuum
    cards:
    - type: vertical-stack
      cards:
        - type: glance
          show_name: false
          entities:
          - entity: vacuum.xiaomi_vacuum_cleaner
        - type: entities
          show_header_toggle: false
          entities:
          - switch.vacuum_hall
          - switch.vacuum_kitchen
          - switch.vacuum_kidsroom
          - switch.vacuum_livingroom
          - input_select.vacuum_fan_speed
          - input_number.vacuum_cleaning_repeats
        - type: glance
          show_state: false
          entities:
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: 'Начать уборку'
            icon: mdi:broom
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.vacuum_zoned_cleanup
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: 'Пауза'
            icon: mdi:pause
            tap_action:
              action: call-service
              service: vacuum.pause
              service_data:
                entity_id: vacuum.xiaomi_vacuum_cleaner
          - entity: vacuum.xiaomi_vacuum_cleaner
            name: 'Вернуться на базу'
            icon: mdi:home
            tap_action:
              action: call-service
              service: vacuum.return_to_base
              service_data:
                entity_id: vacuum.xiaomi_vacuum_cleaner

  - title: 'Сервер'
    icon: mdi:server
    path: server
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Transmission
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.transmission_down_speed
                name: 'Скачивание'
                icon: mdi:arrow-down-bold
                graph: line
              - type: sensor
                entity: sensor.transmission_up_speed
                name: 'Загрузка'
                icon: mdi:arrow-up-bold
                graph: line
          - type: entities
            entities:
              - entity: switch.transmission
              - entity: sensor.transmission_status
                name: 'Статус'
              - entity: sensor.transmission_total_torrents
                name: 'Всего'
                icon: mdi:sigma
              - entity: sensor.transmission_active_torrents
                name: 'Активно'
                icon: mdi:play
              - entity: sensor.transmission_started_torrents
                name: 'Скачивается'
                icon: mdi:arrow-down-bold
              - entity: sensor.transmission_paused_torrents
                name: 'Приостановлено'
                icon: mdi:pause
              - entity: sensor.transmission_completed_torrents
                name: 'Завершено'
                icon: mdi:flag-checkered
      - type: entities
        title: 'Сервер'
        show_header_toggle: false
        entities:
          - entity: switch.server
            icon: mdi:server
          - entity: switch.server_automation
            icon: mdi:power

  - title: 'Батарейки'
    icon: mdi:battery
    path: batteries
    cards:
      - type: entities
        title: 'Прихожая'
        show_header_toggle: false
        entities:
          - sensor.hall_door_battery
          - sensor.hall_sensor_battery
      - type: entities
        title: 'Кухня'
        show_header_toggle: false
        entities:
          - sensor.0x00158d0002236dfb_battery
          - sensor.0x00158d0001a24e62_battery
      - type: entities
        title: 'Детская'
        show_header_toggle: false
        entities:
          - sensor.kitchen_sensor_battery
          - sensor.0x00158d0001e42e65_battery
      - type: entities
        title: 'Гостиная'
        show_header_toggle: false
        entities:
          - sensor.livingroom_door_battery
          - sensor.livingroom_sensor_battery
          - sensor.livingroom_smoke_battery
          - sensor.livingroom_miflora_battery
      - type: entities
        title: 'Ванная'
        show_header_toggle: false
        entities:
          - sensor.bathroom_water_leak_battery
      - type: entities
        title: 'Спальня'
        show_header_toggle: false
        entities:
          - sensor.bedroom_switch_battery
          - sensor.bedroom_button_battery

  - title: 'Zigbee2mqtt'
    icon: mdi:zigbee
    path: zigbee2mqtt
    cards:
      - type: entities
        title: 'Zigbee2mqtt'
        show_header_toggle: false
        entities:
          - entity: sensor.zigbee2mqtt_version
            name: 'Версия'
            icon: mdi:information-outline
          - entity: sensor.zigbee2mqtt_bridge_state
            name: 'Статус'
          - entity: sensor.zigbee_coordinator_version
            name: 'Прошивка координатора'
          - entity: switch.zigbee2mqtt_permit_join
            name: 'Разрешить подключение новых устройств'
            icon: mdi:access-point
          - entity: timer.zigbee2mqtt_permit_join
            name: 'Оставшееся время'
      - type: entities
        title: 'Выключатель в гостиной'
        show_header_toggle: false
        entities:
          - sensor.livingroom_switch_state_left
          - input_select.livingroom_switch_mode_left
          - sensor.livingroom_switch_state_right
          - input_select.livingroom_switch_mode_right