- alias: 'kitchen light on'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.kitchen_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
      after_offset: -01:00:00
    - condition: state
      entity_id: switch.plug_158d00019ccab8
      state: 'off'
    - condition: state
      entity_id: group.person
      state: home
  action:
  - service: switch.turn_on
    entity_id: switch.plug_158d00019ccab8