- alias: 'kitchen_light_on'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.kitchen_motion_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.person
        state: home
      - condition: state
        entity_id: switch.0x00158d00019ccab8_switch
        state: 'off'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-01:00:00'
          - condition: and
            conditions:
              - condition: sun
                after: sunset
                after_offset: '-02:00:00'
              - condition: state
                entity_id: weather.dark_sky
                state: cloudy
  action:
  - service: switch.turn_on
    entity_id: switch.0x00158d00019ccab8_switch