platform: rest
resource: https://cdsvyatka.com/api/kirov/prediction/317
name: public_transport_stop_317
scan_interval: 180
headers:
  Referer: https://cdsvyatka.com/kirov/map
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15
value_template: >
  {{ value_json | selectattr("number", "in", "4, 51") | list }}