platform: template
sensors:
  sun_sunrise:
    friendly_name: Восход
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'

  sun_sunset:
    friendly_name: Закат
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
