platform: template
sensors:

  livingroom_miflora_battery:
    friendly_name: 'Датчик растений'
    value_template: >
      {% if is_state('sensor.mi_flora_battery', 'unknown') %}
          0
      {% else %}
        {{ states('sensor.mi_flora_battery') }}
      {% endif %}
    icon_template: >
      {% set battery_level = states('sensor.mi_flora_battery') | default(0) | int %}
      {% set battery_round = (battery_level / 10) | round(0) | int * 10 %}
      {% if battery_round >= 100 or is_state('sensor.mi_flora_battery', 'unknown') %}
        mdi:battery-bluetooth
      {% elif battery_round > 0 %}
        mdi:battery-{{ battery_round }}-bluetooth
      {% else %}
        mdi:battery-outline
      {% endif %}
    unit_of_measurement: '%'

  livingroom_tv_source:
    friendly_name: 'Источник для телевизора в гостиной'
    value_template: "{{ state_attr('media_player.livingroom_tv', 'source') }}"

  sun_sunrise:
    friendly_name: Восход
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'

  sun_sunset:
    friendly_name: Закат
    value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'

  livingroom_switch_state_left:
    icon_template: mdi:information-outline
    friendly_name: 'Статус левого выключателя'
    value_template: "{{ state_attr('sensor.0x00158d0001715c96_click', 'state_left') }}"

  livingroom_switch_state_right:
    icon_template: mdi:information-outline
    friendly_name: 'Статус правого выключателя'
    value_template: "{{ state_attr('sensor.0x00158d0001715c96_click', 'state_right') }}"