device_tracker:
  platform: nmap_tracker
  home_interval: 30
  hosts:
    - 10.0.0.5
    - 10.0.0.10
    - 10.0.0.56
    - 10.0.0.90
    - 10.0.0.158
    - 10.0.0.248

person:
  - name: Rostislav
    id: rostislav
    user_id: 7c6ea3df58824829b8febfaede0223d8
    device_trackers:
      - device_tracker.rost_watch
      - device_tracker.rost_phone
      - device_tracker.rost_laptop
      - device_tracker.iphone
  - name: Jana
    id: jana
    user_id: 3ee3843636544399a445855ea06ea724
    device_trackers:
      - device_tracker.jana_phone
      - device_tracker.jana_laptop
      - device_tracker.iphone_2
  - name: nina
    id: nina
    device_trackers:
      - device_tracker.nina_phone
