yeelight:
  devices:
    10.0.0.243:
      name: kidsroom_ceiling_light
      model: ceiling4
      use_music_mode: false
      save_on_change: false

light:
  platform: template
  lights:
    kidsroom_light:
      friendly_name: 'Свет в детской'
      value_template: "{{ is_state('binary_sensor.kidsroom_ceiling_light_nightlight', 'off') and is_state('light.kidsroom_ceiling_light', 'on') }}"
      turn_on:
        - service: yeelight.set_mode
          data:
            entity_id: light.kidsroom_ceiling_light
            mode: 'normal'
        - service: light.turn_off
          entity_id: light.kidsroom_ceiling_light_ambilight
      turn_off:
        service: light.turn_off
        entity_id: light.kidsroom_ceiling_light, light.kidsroom_ceiling_light_ambilight
      set_level:
        service: light.turn_on
        data_template:
          entity_id: light.kidsroom_ceiling_light
          brightness: "{{ brightness }}"

    kidsroom_nightlight:
      friendly_name: 'Ночник в детской'
      value_template: "{{ is_state('binary_sensor.kidsroom_ceiling_light_nightlight', 'on') and is_state('light.kidsroom_ceiling_light', 'on') }}"
      turn_on:
        service: yeelight.set_mode
        data:
          entity_id: light.kidsroom_ceiling_light
          mode: 'moonlight'
      turn_off:
        service: light.turn_off
        entity_id: light.kidsroom_ceiling_light
      set_level:
        service: light.turn_on
        data_template:
          entity_id: light.kidsroom_ceiling_light
          brightness: "{{ brightness }}"

automation:
  - alias: 'kidsroom_nightlight_turn_off_after_sunrise'
    trigger:
      platform: sun
      event: sunrise
      offset: '+02:00:00'
    condition:
      condition: state
      entity_id: light.kidsroom_nightlight
      state: 'on'
    action:
      service: light.turn_off
      entity_id: light.kidsroom_nightlight