webostv:
  host: 10.0.0.162
  name: livingroom_tv
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webost_tv_mac
  customize:
    sources:
      - Plex
      - YouTube
      - Apple TV

automation:
  - alias: 'livingroom_tv_turn_off_on_plex_idle'
    trigger:
      platform: state
      entity_id: media_player.plex_plex_lg_oled55b7v_z
      to: 'idle'
      for: '00:15:00'
    condition:
      condition: template
      value_template: "{{ is_state_attr('media_player.livingroom_tv', 'source', 'Plex') }}"
    action:
      service: media_player.turn_off
      entity_id: media_player.livingroom_tv
