input_select:
  livingroom_wall_switch_mode_left:
    name: 'Режим работы левой клавиши'
    icon: mdi:light-switch
    options:
    - control_left_relay
    - control_right_relay
    - decoupled
    initial: control_left_relay
  livingroom_wall_switch_mode_right:
    name: 'Режим работы правой клавиши'
    icon: mdi:light-switch
    options:
    - control_left_relay
    - control_right_relay
    - decoupled
    initial: control_right_relay

automation:
  - alias: 'livingroom_wall_switch_left_button_click'
    trigger:
      platform: state
      entity_id: sensor.0x00158d0001715c96_click
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ trigger.to_state.state == 'left' }}"
    action:
      - service: light.toggle
        entity_id: light.livingroom_light
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ is_state_attr(trigger.entity_id, 'operation_mode_left', 'decoupled') }}"
          - condition: state
            entity_id: switch.0x00158d0001715c96_switch_left
            state: 'off'
      - service: switch.turn_on
        entity_id: switch.0x00158d0001715c96_switch_left

  - alias: 'livingroom_wall_switch_left_button_set_decoupled_mode'
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: switch.0x00158d0001715c96_switch_left
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ state_attr('sensor.0x00158d0001715c96_click', 'operation_mode_left') != 'decoupled' }}"
        - condition: state
          entity_id: switch.0x00158d0001715c96_switch_left
          state: 'on'
    action:
      service: script.livingroom_wall_switch_set_operation_mode
      data_template:
        switch_id: '0x00158d0001715c96'
        button: 'left'
        operation_mode: 'decoupled'

  - alias: 'livingroom_wall_switch_left_button_set_relay_mode'
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      service: script.livingroom_wall_switch_set_operation_mode
      data_template:
        switch_id: '0x00158d0001715c96'
        button: 'left'
        operation_mode: 'control_left_relay'

  - alias: 'livingroom_wall_switch_left_set_operation_mode'
    trigger:
      platform: state
      entity_id: input_select.livingroom_wall_switch_mode_left
    action:
      service: script.livingroom_wall_switch_set_operation_mode
      data_template:
        switch_id: '0x00158d0001715c96'
        button: 'left'
        operation_mode: "{{ trigger.to_state.state }}"

  - alias: 'livingroom_wall_switch_right_set_operation_mode'
    trigger:
      platform: state
      entity_id: input_select.livingroom_wall_switch_mode_right
    action:
      service: script.livingroom_wall_switch_set_operation_mode
      data_template:
        switch_id: '0x00158d0001715c96'
        button: 'right'
        operation_mode: "{{ trigger.to_state.state }}"

script:
  livingroom_wall_switch_set_operation_mode:
    description: 'Установка режима работы проводного выключателя Aqara'
    fields:
      switch_id:
        description: 'Идентификатор выключателя'
        example: '0x00158d0001715c96'
      button:
        description: 'Клавиша'
        example: 'single | left | right'
      operation_mode:
        description: 'Режим работы'
        example: 'control_relay | control_left_relay | control_right_relay | decoupled'
    sequence:
      - service: mqtt.publish
        data_template:
          topic: 'zigbee2mqtt/{{ switch_id }}/system/set'
          payload: >-
            {
              "operation_mode": {
                "button": "{{ button }}",
                "state": "{{ operation_mode }}"
              }
            }
      - service: logbook.log
        data_template:
          name: 'Script:'
          message: 'switch "{{ switch_id }}" button "{{ button }}" changed to "{{ operation_mode }}" mode'
      - delay: '00:00:01'
      - service: mqtt.publish
        data_template:
          topic: 'zigbee2mqtt/{{ switch_id }}/system/get'
          payload: >-
            {
              "operation_mode": {
                "button": "{{ button }}"
              }
            }