type: entities
title: "Прихожая"
show_header_toggle: false
entities:
  - entity: binary_sensor.doorbell_sound
    name: "Звонок"
    icon: mdi:bell-ring
  - entity: binary_sensor.0x00158d0001b14504
    name: "Дверь"
    secondary_info: last-changed
  - entity: binary_sensor.0x00158d0001e523ab_occupancy
    name: "Движение"
    secondary_info: last-changed
  - entity: light.hall_ceiling_light
    name: "Свет"
  - entity: light.hall_ceiling_light_nightlight
    name: "Ночник"
  - entity: binary_sensor.0x00158d00041d5e14_contact
    name: "Дверь шкафа"
    icon: mdi:cupboard-outline
