- alias: 'livingroom_ceiling_light_ambilight'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.livingroom_tv_source
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.livingroom_ceiling_light
        state: 'on'
      - condition: state
        entity_id: light.livingroom_ceiling_light_ambilight
        state: 'on'
  action:
    service: scene.turn_on
    data_template:
      entity_id: >
        {%- if is_state('sensor.livingroom_tv_source', 'Plex') %}
          scene.livingroom_ambilight_plex
        {%- elif is_state('sensor.livingroom_tv_source', 'YouTube') %}
          scene.livingroom_ambilight_youtube
        {%- endif %}