- alias: 'livingroom_tv_moonlight'
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: template
    value_template: "{{ is_state_attr('media_player.livingroom_tv', 'source', 'Plex') }}"
  condition:
    condition: state
    entity_id: light.livingroom_ceiling_light
    state: 'on'
  action:
     - service: light.turn_on
       data:
         entity_id: light.livingroom_ceiling_light_ambilight
         effect: 'Plex'
     - service: light.turn_off
       data:
         entity_id: light.livingroom_ceiling_light