- alias: 'livingroom_tv_notify_eat_off'
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion_sensor
    to: 'off'
    for:
      minutes: 6
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.notify_livingroom_tv_eat