- alias: 'livingroom_tv_notify_eat_on'
  initial_state: 'off'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion_sensor
    to: 'off'
    for:
      minutes: 1
  condition:
    condition: state
    entity_id: device_tracker.f86fc1ef4425
    state: home
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.notify_livingroom_tv_eat