- alias: 'livingroom_tv_pause'
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010ed5cf_2
      action_type: tap_twice
  action:
  - service: media_player.media_play_pause
    data:
      entity_id: media_player.livingroom_tv