- alias: 'livingroom_tv_volume'
  initial_state: 'on'
  hide_entity: true
  trigger:
  - platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00010ed5cf_2
      action_type: rotate
  action:
  - service_template: >
      {%if trigger.event.data.action_value | float > 0 %}
        media_player.volume_up
      {% else %}
        media_player.volume_down
      {% endif %}
    data:
      entity_id: media_player.livingroom_tv