- alias: 'server_turn_on_when_someone_comes'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.person
    to: home
  condition:
    condition: state
    entity_id: switch.server
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.server