- alias: 'server_turn_on_when_tv_on'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.livingroom_tv
    to: playing
  - platform: state
    entity_id: media_player.kitchen_tv
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: switch.server
      state: 'off'
    - condition: state
      entity_id: group.person
      state: 'home'
  action:
  - service: switch.turn_on
    entity_id: switch.server