- alias: 'server turn on when someone comes'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.person
    to: home
  condition:
    condition: state
    entity_id: switch.rock_home
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.rock_home