- alias: 'server_turn_on_when_tv_on'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.livingroom_tv
    to: 'playing'
  - platform: state
    entity_id: media_player.kitchen_tv
    to: 'on'
  condition:
    condition: state
    entity_id: switch.server
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.server