- alias: 'server turn off'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: group.person
    to: not_home
    for:
      minutes: 15
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: media_player.kitchen_tv
      state: 'off'
    - condition: state
      entity_id: media_player.livingroom_tv
      state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.rock_home