platform: template
lights:

  bedroom_daylight:
    friendly_name: 'Свет'
    value_template: >
      {% if is_state('light.bedroom_mono', 'on') %}
        on
      {% else %}
        off
      {% endif %}
    turn_on:
    - service: scene.turn_on
      entity_id: scene.bedroom_daylight
    turn_off:
    - service: light.turn_off
      entity_id: group.bedroom_light

  bedroom_nightlight:
    friendly_name: 'Ночник'
    value_template: >
      {% if is_state('light.bedroom_color', 'off') or is_state('light.bedroom_color', '') %}
        off
      {% elif is_state_attr('light.bedroom_color', 'brightness', 255) %}
        off
      {% else %}
        on
      {% endif %}
    turn_on:
     - service: scene.turn_on
       entity_id: scene.bedroom_nightlight
    turn_off:
    - service: light.turn_off
      entity_id: group.bedroom_light

  livingroom_nightlight:
    turn_on:
    - service: light.yeelight_set_mode
      data:
        entity_id: light.livingroom_ceiling_light
        mode: 'moonlight'
    turn_off:
    - service: light.yeelight_set_mode
      data:
        entity_id: light.livingroom_ceiling_light
        mode: 'normal'