platform: template
lights:

  kidsroom_nightlight:
    friendly_name: 'Ночник в детской'
    value_template: "{{ state_attr('light.kidsroom_ceiling_light', 'color_temp')|int > 0 }}"
    turn_on:
    - service: yeelight.set_mode
      data:
        entity_id: light.kidsroom_ceiling_light
        mode: 'moonlight'
    turn_off:
    - service: light.turn_off
      entity_id: light.kidsroom_ceiling_light

  livingroom_nightlight:
    friendly_name: 'Ночник в гостиной'
    value_template: "{{ state_attr('light.livingroom_ceiling_light', 'color_temp')|int > 0 }}"
    turn_on:
    - service: yeelight.set_mode
      data:
        entity_id: light.livingroom_ceiling_light
        mode: 'moonlight'
    turn_off:
    - service: light.turn_off
      entity_id: light.livingroom_ceiling_light

  bedroom_daylight:
    friendly_name: 'Свет в спальне'
    value_template: "{{ is_state('light.bedroom_mono', 'on') }}"
    turn_on:
    - service: scene.turn_on
      entity_id: scene.bedroom_daylight
    turn_off:
    - service: light.turn_off
      entity_id: group.bedroom_light

  bedroom_nightlight:
    friendly_name: 'Ночник в спальне'
    value_template: >
      {% if is_state('light.bedroom_color', 'off') or is_state('light.bedroom_color', '') %}
        off
      {% elif is_state_attr('light.bedroom_color', 'brightness', 255) %}
        off
      {% else %}
        on
      {% endif %}
    turn_on:
      - service: scene.turn_on
        entity_id: scene.bedroom_nightlight
    turn_off:
      - service: light.turn_off
        entity_id: group.bedroom_light