name: 'livingroom_ambilight_youtube'
entities:
  light.livingroom_ceiling_light_ambilight:
    state: true
    rgb_color: [225,0,0]
    transition: 3
    brightness_pct: 1
  light.livingroom_ceiling_light:
    state: false
    transition: 2